{% set name = "libmongocxx" %}
{% set version = "3.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-cxx-driver/releases/download/r{{ version }}/mongo-cxx-driver-r{{ version }}.tar.gz
  sha256: fb2da11178db728f63147fe4b0c7509eb49b1b02c5cb55f9bee5f927e451a0c7

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - boost-cpp
    - libbson
    - libmongoc

test:
  commands:
    - test -f ${PREFIX}/include/mongocxx/v_noabi/mongocxx/client.hpp    # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libmongocxx.pc         # [unix]
    - test -f ${PREFIX}/lib/libmongocxx${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\mongocxx\v_noabi\mongocxx\client.hpp (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\mongocxx.lib (exit 1)    # [win]
    - if not exist %LIBRARY_BIN%\mongocxx.dll (exit 1)    # [win]

about:
  home: https://github.com/mongodb/mongo-cxx-driver
  license: Apache-2.0
  license_file: LICENSE
  summary: The mongocxx is a ground-up rewrite of a C++ driver for MongoDB based on libmongoc.

extra:
  recipe-maintainers:
    - Tobias-Fischer
